import Mathlib

/-!
# AQARION JOIN-STABILITY

Formalization target:
  1. finite pullback rigidity;
  2. finite join stability.

Status: OPEN.
The `sorry` declarations below are intentional, visible blockers.
This file is not evidence of a completed Lean proof.
-/

namespace AQARION.JoinStability

variable {α : Type*} [Fintype α] [DecidableEq α]

/-- Pullback of a binary relation along a map. -/
def Pullback (T : α → α) (R : α → α → Prop) : α → α → Prop :=
  fun x y => R (T x) (T y)

/-- Pullback stability: related images imply related original points. -/
def PullbackStable (T : α → α) (R : α → α → Prop) : Prop :=
  ∀ ⦃x y : α⦄, R (T x) (T y) → R x y

/-- The relation generated by the union of two relations. -/
def Join (E F : α → α → Prop) : α → α → Prop :=
  Relation.ReflTransGen (fun x y => E x y ∨ F x y)

/-- Finite pullback rigidity target. -/
theorem finite_pullback_rigidity
    (T : α → α)
    (E : α → α → Prop)
    (hE : Equivalence E)
    (hstable : PullbackStable T E) :
    ∀ x y, E (T x) (T y) ↔ E x y := by
  intro x y
  constructor
  · intro h
    exact hstable h
  · intro h
    sorry

/-- Join stability target; requires the equivalence relations E and F. -/
theorem finite_join_stability
    (T : α → α)
    (E F : α → α → Prop)
    (hE : Equivalence E)
    (hF : Equivalence F)
    (hstableE : PullbackStable T E)
    (hstableF : PullbackStable T F) :
    PullbackStable T (Join E F) := by
  sorry

end AQARION.JoinStability
