from enum import Enum


class Status(str, Enum):
    OPEN = "OPEN"
    CANDIDATE = "CANDIDATE"
    COMPUTATIONALLY_VERIFIED = "COMPUTATIONALLY_VERIFIED"
    PAPER_PROVED = "PAPER_PROVED"
    FORMALLY_VERIFIED = "FORMALLY_VERIFIED"
    RETRACTED = "RETRACTED"
    BLOCKED = "BLOCKED"
    QUARANTINED = "QUARANTINED"
